name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci-shape.yml
    with:
      build-steps: |
        [
          {
            "name": "Install dependencies (Node.js)",
            "run": "npm ci",
            "if": "hashFiles('package.json') != ''"
          },
          {
            "name": "Install dependencies (Python)",
            "run": "python -m pip install --upgrade pip && pip install -r requirements.txt",
            "if": "hashFiles('requirements.txt') != ''"
          },
          {
            "name": "Run tests (Node.js)",
            "run": "npm test",
            "if": "hashFiles('package.json') != ''"
          },
          {
            "name": "Run tests (Python)",
            "run": "python -m pytest",
            "if": "hashFiles('requirements.txt') != '' || hashFiles('pyproject.toml') != ''"
          },
          {
            "name": "Lint check",
            "run": "echo 'Running basic lint checks...'\n# Add your linting commands here"
          },
          {
            "name": "Build project",
            "run": "echo 'Building project...'\n# Add your build commands here"
          },
          {
            "name": "Publish artifacts",
            "run": "echo 'Publishing build artifacts...'\n# Add your publish commands here"
          }
        ]
      deploy-dev-steps: |
        [
          {
            "name": "Deploy to dev",
            "run": "echo 'hi'"
          }
        ]
      deploy-test-steps: |
        [
          {
            "name": "Deploy to test",
            "run": "echo 'hi'"
          }
        ]
      deploy-prod-steps: |
        [
          {
            "name": "Deploy to prod",
            "run": "echo 'hi'"
          }
        ]
      node-version: '18'
      python-version: '3.9'
