name: Dependency Update Check

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
      if: hashFiles('package.json') != ''
      
    - name: Check for outdated dependencies (Node.js)
      run: |
        echo "Checking for outdated Node.js dependencies..."
        npm outdated || true
      if: hashFiles('package.json') != ''
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      if: hashFiles('requirements.txt') != ''
      
    - name: Check for outdated dependencies (Python)
      run: |
        echo "Checking for outdated Python dependencies..."
        pip install pip-check-updates
        pip list --outdated || true
      if: hashFiles('requirements.txt') != ''
      
    - name: Security audit (Node.js)
      run: |
        echo "Running security audit..."
        npm audit || true
      if: hashFiles('package.json') != ''
      
    - name: Create issue if vulnerabilities found
      uses: actions/github-script@v7
      with:
        script: |
          const title = 'Security vulnerabilities detected';
          const body = 'Automated security scan found potential vulnerabilities. Please review and update dependencies.';
          
          // Check if issue already exists
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: ['security', 'dependencies']
          });
          
          if (issues.data.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'dependencies']
            });
          }
